# Stage 1: Build the Go application
FROM golang:1.24.5-alpine AS builder

WORKDIR /app

COPY go.mod .
COPY .env .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o main .

# Stage 2: Create the final, smaller image
FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/.env .
EXPOSE 1234

CMD ["./main"]